# Generated by Django 3.0.7 on 2020-07-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
    ]
