# Generated by Django 3.0.7 on 2020-07-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.TextField(default='default'),
        ),
    ]
