# Generated by Django 3.0.7 on 2020-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200714_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
