# Generated by Django 3.0.7 on 2020-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200923_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(blank=True, verbose_name='Позиция'),
        ),
    ]
